import { useEffect, useState } from "react";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useSearchParams } from "react-router-dom";

import { EmptyState } from "@/components/ui/EmptyState";
import { PageCard } from "@/components/ui/PageCard";
import { formatDateTime } from "@/lib/format/date";
import { readBooleanParam, readNumberParam, writeParam } from "@/lib/routing/searchParams";
import { notificationKeys } from "@/services/notifications/notifications.keys";
import { listNotifications, markNotificationRead } from "@/services/notifications/notifications.service";
import type { NotificationFilters } from "@/services/notifications/notifications.types";

/**
 * Hosts the notifications route.
 *
 * @returns The placeholder notifications screen.
 */
export const NotificationsPage = (): JSX.Element => {
    const queryClient = useQueryClient();
    const [searchParams, setSearchParams] = useSearchParams();
    const filters: NotificationFilters = {
        limit: readNumberParam(searchParams, "limit", 50),
        unread_only: readBooleanParam(searchParams, "unread_only", false),
    };
    const [unreadOnly, setUnreadOnly] = useState(filters.unread_only);
    const [limit, setLimit] = useState(`${filters.limit}`);
    const notificationsQuery = useQuery({
        queryFn: () => {
            return listNotifications(filters);
        },
        queryKey: notificationKeys.list(filters),
    });
    const markReadMutation = useMutation({
        mutationFn: markNotificationRead,
        onSuccess() {
            void queryClient.invalidateQueries({ queryKey: ["me", "notifications"] });
        },
    });

    useEffect(() => {
        setUnreadOnly(filters.unread_only);
        setLimit(`${filters.limit}`);
    }, [filters.limit, filters.unread_only]);

    return (
        <div className={"page-stack"}>
            <PageCard description={"Notifications are generated by the backend from watchlist and alert-rule matches during ingestion."} title={"Notifications"}>
                <form
                    className={"form-grid form-grid--inline"}
                    onSubmit={(event) => {
                        event.preventDefault();
                        const nextParams = new URLSearchParams(searchParams);
                        writeParam(nextParams, "unread_only", `${unreadOnly}`);
                        writeParam(nextParams, "limit", limit);
                        setSearchParams(nextParams);
                    }}
                >
                    <label className={"field field--checkbox"}>
                        <input checked={unreadOnly} onChange={(event) => { setUnreadOnly(event.target.checked); }} type={"checkbox"} />
                        <span className={"field__label"}>{"Unread only"}</span>
                    </label>

                    <label className={"field"}>
                        <span className={"field__label"}>{"Limit"}</span>
                        <input className={"field__control"} min={1} onChange={(event) => { setLimit(event.target.value); }} step={1} type={"number"} value={limit} />
                    </label>

                    <div className={"field field--actions"}>
                        <button className={"button"} type={"submit"}>{"Apply"}</button>
                    </div>
                </form>
            </PageCard>

            <PageCard description={"Notification payloads are rendered as title and body first, with raw metadata available when present."} title={"Inbox"}>
                {notificationsQuery.isLoading ? <p className={"muted-copy"}>{"Loading notifications..."}</p> : null}
                {notificationsQuery.isError ? <p className={"error-banner"}>{"Could not load notifications."}</p> : null}
                {notificationsQuery.isSuccess && notificationsQuery.data.items.length === 0 ? <EmptyState message={"No notifications matched the current filters."} /> : null}
                {notificationsQuery.data !== undefined && notificationsQuery.data.items.length > 0 ? (
                    <div className={"item-list"}>
                        {notificationsQuery.data.items.map((item) => {
                            return (
                                <article className={"list-row"} key={item.id}>
                                    <div className={"list-row__main"}>
                                        <div>
                                            <h3 className={"list-row__title"}>{item.title}</h3>
                                            <p className={"list-row__meta"}>{item.body}</p>
                                        </div>
                                        <strong className={"list-row__price"}>{item.kind}</strong>
                                    </div>
                                    <div className={"list-row__footer"}>
                                        <span>{item.read_at === undefined ? "Unread" : `Read ${formatDateTime(item.read_at)}`}</span>
                                        <span>{"Created "}{formatDateTime(item.created_at)}</span>
                                        {item.read_at === undefined ? (
                                            <button
                                                className={"button button--secondary"}
                                                disabled={markReadMutation.isPending}
                                                onClick={() => {
                                                    markReadMutation.mutate(item.id);
                                                }}
                                                type={"button"}
                                            >
                                                {"Mark read"}
                                            </button>
                                        ) : null}
                                    </div>
                                </article>
                            );
                        })}
                    </div>
                ) : null}
            </PageCard>
        </div>
    );
};